### ISSUE TITLE
JSON syntax: comments, values

### ISSUE THREAD

**Issue by fredrikaverpil** [mgyongyosi/OneDarkJekyll#2]
Not a big issue, but comments are rendered in a quite unreadable color. I also notice the JSON values are rendered in a different color than expected.

![screen shot 2017-02-04 at 21 45 36](https://cloud.githubusercontent.com/assets/994357/22621493/72b1d210-eb25-11e6-832b-0430016bf448.png)

Here's what I believe it should look like (taken from Atom):

![screen shot 2017-02-04 at 21 59 55](https://cloud.githubusercontent.com/assets/994357/22621496/78cf63d8-eb25-11e6-961b-fd128f08db6b.png)

**Comment by mgyongyosi** [comment]
Hi @fredrikaverpil,

I have already updated the syntax.less file to support custom coloring by language. Currently JSON highlighting is almost the same as in Atom. Almost, because Rouge highlighter is not as detailed/specific like Atom's syntax highlighter.

Also, added the __language-python__ selector to the syntax.less file if you would like to jump in and complete the python specific changes.
